### PR TITLE
Use min-indent

### PR DESCRIPTION
**Pull request by thejameskyle**
I needed to use the first part of this logic for another module I'm working on. So I split it out into a [`min-indent` package](https://github.com/thejameskyle/min-indent). I figured I'd add it to this package as well.

Also @sindresorhus, if you want to have the repo/package I'm happy to transfer it to you. I purposefully copied your setup.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Also @sindresorhus, if you want to have the repo/package I'm happy to transfer it to you. I purposefully copied your setup.

Not needed, but would be cool if you could add me to the repo and npm package though.

**Comment by sindresorhus** [comment]
> I needed to use the first part of this logic for another module I'm working on.

Let me know when it's out. I'm curious about what other use-cases there are :)

**Comment by thejameskyle** [comment]
Added you to min-indent

Also, I'm using it for comment normalization in ASTs

```js
"    /**\n     * test\n     */" <-> "test"
```

**Comment by sindresorhus** [comment]
Neat

**Pull request merged**
